sudo: required
dist: trusty
language: node_js
node_js:
- 6.2.2
- 4.4.5
cache:
  directories:
  - node_modules
branches:
  except:
  - "/^v[0-9\\.]+/"
install:
- travis_retry npm install
script:
- npm test